# Generated by Django 5.2.7 on 2025-10-21 21:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(db_index=True, max_length=64)),
                ('board_size', models.PositiveIntegerField(default=10)),
                ('words', models.JSONField(default=list)),
                ('soup', models.JSONField(default=list)),
                ('dict_word_position', models.JSONField(default=dict)),
                ('found_words', models.JSONField(default=list)),
                ('locked_cells', models.JSONField(default=list)),
                ('progress_pct', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('active_selections', models.JSONField(default=dict)),
            ],
        ),
    ]
