# Generated by Django 5.2.7 on 2025-10-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapasJuego', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(default=1)),
                ('titulo', models.CharField(max_length=150)),
                ('historia', models.TextField(help_text='Texto narrativo del desafío o problemática.')),
                ('personaje', models.CharField(max_length=100)),
                ('imagen_personaje', models.ImageField(blank=True, help_text='Imagen del personaje asociado.', null=True, upload_to='desafios/')),
                ('duracion_min', models.PositiveSmallIntegerField(default=3)),
                ('etapa', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
