# Generated by Django 5.2.7 on 2025-11-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapasJuego', '0002_desafio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='imagen_personaje',
            field=models.ImageField(blank=True, null=True, upload_to='desafios/'),
        ),
        migrations.AlterField(
            model_name='teamgamesession',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
