# Generated by Django 5.2.7 on 2025-11-24 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapasJuego', '0003_alter_desafio_imagen_personaje_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_general', models.CharField(choices=[('SALUD', 'Salud'), ('SUST', 'Sustentabilidad'), ('EDU', 'Educación')], max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tema_general', models.CharField(choices=[('SALUD', 'Salud'), ('SUST', 'Sustentabilidad'), ('EDU', 'Educación')], max_length=10)),
                ('etapa_actual', models.CharField(default='ETAPA1', max_length=20)),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_juego', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen_idea', models.TextField(blank=True)),
                ('foto_prototipo', models.ImageField(blank=True, null=True, upload_to='prototipos/')),
                ('foto_grupal', models.ImageField(blank=True, null=True, upload_to='fotos_grupales/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='etapasJuego.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guion', models.TextField(blank=True)),
                ('sugerencias_ia', models.TextField(blank=True)),
                ('tiempo_preparacion_seg', models.PositiveIntegerField(default=360)),
                ('tiempo_presentacion_seg', models.PositiveIntegerField(default=90)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pitch', to='etapasJuego.project')),
            ],
        ),
        migrations.CreateModel(
            name='EmpathyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gustos', models.TextField(blank=True)),
                ('problemas', models.TextField(blank=True)),
                ('miedos', models.TextField(blank=True)),
                ('contexto', models.TextField(blank=True)),
                ('datos_extra', models.JSONField(blank=True, null=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapa_empatia', to='etapasJuego.project')),
            ],
        ),
        migrations.CreateModel(
            name='CreativityActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_solucion', models.TextField(blank=True)),
                ('restricciones', models.TextField(blank=True)),
                ('notas_equipo', models.TextField(blank=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_creatividad', to='etapasJuego.project')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_grupo', models.CharField(max_length=1)),
                ('tokens_empatia', models.PositiveIntegerField(default=0)),
                ('tokens_creatividad', models.PositiveIntegerField(default=0)),
                ('tokens_evaluacion', models.PositiveIntegerField(default=0)),
                ('tokens_totales', models.PositiveIntegerField(default=0)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='etapasJuego.gamesession')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='equipo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='etapasJuego.team'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_equipo', models.PositiveIntegerField()),
                ('puntaje_empatia', models.PositiveIntegerField()),
                ('puntaje_creatividad', models.PositiveIntegerField()),
                ('puntaje_comunicacion', models.PositiveIntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='etapasJuego.gamesession')),
                ('evaluado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_recibidas', to='etapasJuego.team')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_realizadas', to='etapasJuego.team')),
            ],
            options={
                'unique_together': {('sesion', 'evaluador', 'evaluado')},
            },
        ),
    ]
