# Generated by Django 5.2.7 on 2025-12-01 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapasJuego', '0004_challenge_gamesession_project_pitch_empathymap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen para mostrar en la tarjeta del tema.', null=True, upload_to='topics/')),
                ('color_hex', models.CharField(blank=True, help_text='Color asociado al tema (ej: #FFCC00).', max_length=7)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='tema_general',
        ),
        migrations.AddField(
            model_name='challenge',
            name='orden',
            field=models.PositiveIntegerField(default=1, help_text='Orden en que se mostrará el desafío dentro del tema.'),
        ),
        migrations.AddField(
            model_name='teamgamesession',
            name='equipo',
            field=models.ForeignKey(blank=True, help_text='Equipo asociado a esta partida de sopa de letras (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wordsearch_sessions', to='etapasJuego.team'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='topic',
            field=models.ForeignKey(default=None, help_text='Tema al que pertenece este desafío.', on_delete=django.db.models.deletion.PROTECT, related_name='desafios', to='etapasJuego.topic'),
            preserve_default=False,
        ),
    ]
