# Generated by Django 5.2.7 on 2025-12-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapasJuego', '0005_topic_remove_challenge_tema_general_challenge_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='video_file',
            field=models.FileField(blank=True, help_text='Archivo de video asociado a este desafío (opcional).', null=True, upload_to='challenge_videos/'),
        ),
    ]
