# Generated by Django 5.2.7 on 2025-12-01 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapasJuego', '0006_challenge_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desafios', to='etapasJuego.challenge'),
        ),
    ]
