# Generated by Django 5.2.7 on 2025-12-01 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapasJuego', '0007_desafio_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='selected_desafio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_selected', to='etapasJuego.desafio'),
        ),
    ]
