# Generated by Django 5.2.7 on 2025-12-02 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapasJuego', '0009_empathymap_hobbies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='tablet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='etapasJuego.tablet'),
        ),
    ]
