# Generated by Django 5.2.7 on 2025-12-02 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapasJuego', '0010_tablet_team_tablet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablet',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tablets', to='etapasJuego.gamesession'),
        ),
    ]
