# Generated by Django 5.2.7 on 2025-12-02 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapasJuego', '0011_tablet_sesion'),
        ('login', '0003_seccionestudiantes_estudiante_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='modo_asignacion',
            field=models.CharField(choices=[('LOGIN_RANDOM', 'Asignación automática en el login'), ('PRECONFIGURADO', 'Asignación preconfigurada por el profesor')], default='LOGIN_RANDOM', max_length=20),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='login.seccionestudiantes'),
        ),
    ]
