# Generated by Django 5.2.7 on 2025-12-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etapasJuego', '0012_gamesession_modo_asignacion_gamesession_seccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='tema_general',
        ),
    ]
