# Generated by Django 5.2.7 on 2025-12-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapasJuego', '0013_remove_gamesession_tema_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablet',
            name='codigo_acceso',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True),
        ),
    ]
