# Generated by Django 5.2.7 on 2025-12-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etapasJuego', '0014_tablet_codigo_acceso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreativityActivity',
        ),
    ]
