# Generated by Django 5.2.7 on 2025-12-02 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapasJuego', '0015_delete_creativityactivity'),
        ('login', '0003_seccionestudiantes_estudiante_seccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.UniqueConstraint(fields=('seccion',), name='unique_gamesession_per_seccion'),
        ),
    ]
