# Generated by Django 5.2.7 on 2025-12-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapasJuego', '0016_gamesession_unique_gamesession_per_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='duracion_etapa1_segundos',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='duracion_etapa2_segundos',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='duracion_etapa3_segundos',
            field=models.PositiveIntegerField(default=900),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='duracion_etapa4_segundos',
            field=models.PositiveIntegerField(default=600),
        ),
    ]
