# Generated by Django 5.2.7 on 2025-12-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapasJuego', '0017_gamesession_duracion_etapa1_segundos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='score_ai',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Puntaje automático 1-5 del pitch según IA.', null=True),
        ),
    ]
