# Generated by Django 5.2.7 on 2025-10-22 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etapasJuego', '0009_empathymap_hobbies'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='grupo',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='etapasJuego.team'),
        ),
    ]
