# Generated by Django 5.2.7 on 2025-12-02 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_seccionestudiantes_estudiante_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='seccionestudiantes',
            name='carrera_fk',
            field=models.ForeignKey(blank=True, help_text='Nueva referencia normalizada a Carrera; preferir este campo sobre el texto legado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secciones', to='login.carrera'),
        ),
    ]
