# Generated by Django 5.2.7 on 2025-12-02 17:36

from django.db import migrations


def forwards_fill_carrera_fk(apps, schema_editor):
    Carrera = apps.get_model("login", "Carrera")
    SeccionEstudiantes = apps.get_model("login", "SeccionEstudiantes")

    for seccion in SeccionEstudiantes.objects.all():
        nombre = (seccion.carrera or "").strip()
        if not nombre:
            continue
        carrera_obj, _ = Carrera.objects.get_or_create(nombre=nombre)
        if seccion.carrera_fk_id != carrera_obj.id:
            seccion.carrera_fk = carrera_obj
            seccion.save(update_fields=["carrera_fk"])


def backwards_clear_carrera_fk(apps, schema_editor):
    SeccionEstudiantes = apps.get_model("login", "SeccionEstudiantes")
    SeccionEstudiantes.objects.update(carrera_fk=None)


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_carrera_seccionestudiantes_carrera_fk'),
    ]

    operations = [
        migrations.RunPython(forwards_fill_carrera_fk, backwards_clear_carrera_fk),
    ]
