# Generated by Django 5.2.7 on 2025-12-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20251202_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='nombre_facultad',
            field=models.CharField(blank=True, help_text='Facultad a la que pertenece esta carrera.', max_length=200),
        ),
    ]
